version: "3.8"
services:

  db:
    image: 'mysql:5.7'
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: main
    ports:
      - 3306:3306
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:5.0
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1081:1080"
      - "1026:1025"
    networks:
      - dev

networks:
  dev: